# Generated by Django 5.0.1 on 2025-06-14 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('business_address', models.TextField()),
                ('primary_phone', models.CharField(max_length=15)),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_type', models.CharField(max_length=200)),
                ('project_handover_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('project_status', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.TextField()),
                ('PhoneNumber', models.IntegerField()),
                ('Designation', models.CharField(max_length=500)),
                ('BranAddress', models.TextField()),
                ('Reporting', models.CharField(max_length=500)),
                ('SignupDate', models.DateField()),
                ('AccountStatus', models.CharField(max_length=100)),
            ],
        ),
    ]
