# Generated by Django 5.0.1 on 2025-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=21000.0, max_digits=10),
        ),
    ]
