# Generated by Django 5.0.1 on 2025-06-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_users_monthly_target'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
