# Generated by Django 5.0.1 on 2025-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_client_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Executive', 'Executive'), ('Team Leader', 'Team Leader'), ('Manager', 'Manager'), ('Admin', 'Admin')], max_length=50)),
                ('department', models.CharField(choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Support', 'Support'), ('Management', 'Management')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
