# Generated by Django 5.0.1 on 2025-06-15 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_payment_options_remove_payment_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
