# Generated by Django 5.0.1 on 2025-06-16 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_target_created_at_target_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='apps.client')),
                ('from_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_clients', to=settings.AUTH_USER_MODEL)),
                ('to_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_clients', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_transfers',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
