# Generated by Django 5.0.1 on 2025-06-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_clienttransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
